### PR TITLE
no clone and cast but proper NextRequest() instantiation

### PR DESCRIPTION
**Pull request by logemann**
otherwise we lose properties like "nextUrl" or "searchPararms" what people want to use in their handlers.

Example: Triggering this cron URL: http://myservice.com/api/foo?data_size=1

And having this handler in NextJS:

```
async function handler(_req: NextRequest) {
  console.log(_req.url);
  console.log(_req.nextUrl);
  console.log(_req.nextUrl.searchParams);
  return ...
}

export const POST = verifySignatureAppRouter(handler);
export const GET = verifyGetInvocation(handler);
```

Will result in the following log:

-> http://myservice.com/api/foo?data_size=1
-> undefined
-> undefined

So basically the user is downgraded to Standard Request object but getting it back as a NextRequest in his handler. Pretty misleading.

### CODE REVIEW

**Comment by logemann** [comment]
Hmmm. Cant be merged as is... Primary problem solved but now i get this:
 ⨯ TypeError: Body is unusable

**Comment by logemann** [comment]
When using 

const reqClone = new NextRequest(req.url);

instead of:

**Comment by ogzhanolguncu** [comment]
@logemann I have to test this thoroughly, then merge it if its good

**Comment by logemann** [comment]
tested and can confirm that when using 
const reqClone = new NextRequest(req.url), we will lose the body, which of course is a non starter. 

When doing: new NextRequest(req), i get:
⨯ ReferenceError: body is not defined

So, i am cluelesss right now.

**Comment by logemann** [comment]
This last commit should do it....

**Comment by ogzhanolguncu** [comment]
> This last commit should do it....

I'll test it and let you know.

**Comment by ogzhanolguncu** [comment]
If you try to `new NextRequest(request)` when passing to handler. It throws like this:

`TypeError: Cannot construct a Request with a Request object that has already been used.`

Since we don't mutate the request object I don't think we need recreate it or clone it. We can directly pass it to handler function. 


I test like this -> https://qstash-test.vercel.app/api/hello-world-1?foo=bar
As you can see down below, now you can safely access those fields.
image

I updated your PR accordingly.

**Review by ogzhanolguncu — APPROVED** [review]

**Comment by logemann** [comment]
can you ping me when the version is in NPM to try it out?

**Comment by ogzhanolguncu** [comment]
@logemann You can start using it at version 2.5.2.

**Comment by jvitormelo** [comment]
Humm, for some reason, after this version, I cannot use the verifySignatureAppRouter, I had to downgrade to 2.5.0
image

**Comment by ogzhanolguncu** [comment]
Can you send me a repo link for reproduction?

**Comment by jvitormelo** [comment]
> Can you send me a repo link for reproduction?

Sorry for the late response, I checked and some person already did
https://github.com/upstash/qstash-js/issues/100

**Pull request merged**
