### PR TITLE
feat: change import paths

### PR DESCRIPTION
**Pull request by ogzhanolguncu**
This PR

- Replaces biome with eslint for stricter linting.
- Adds prettier.js
- Adds bun for test and runtime
- Unidici for header and body types
- Husky for hooks
- Commitlint for stricter commit conventions
- Fixes import paths. imports no longer require `/dist/nextjs` or `/dist`.  This might break existing import paths.

### CODE REVIEW

**Comment by MeshanKhosla** [comment]
Looks like this does cause existing imports to be broken. Followed the [Nextjs quickstart](https://upstash.com/docs/qstash/quickstarts/vercel-nextjs) and got this after step 5.

```
Package path ./dist/nextjs is not exported from package 
```

Also getting this type error

```
Argument of type '(request: Request) => Promise<Response>' is not assignable to parameter of type '((request: Request) => VerifySignatureAppRouterResponse) | ((request: NextRequest) => VerifySignatureAppRouterResponse)'.
  Type '(request: Request) => Promise<Response>' is not assignable to type '(request: Request) => VerifySignatureAppRouterResponse'.
    Type 'Promise<Response>' is not assignable to type 'VerifySignatureAppRouterResponse'.
      Type 'Promise<Response>' is not assignable to type 'Promise<NextResponse<unknown>>'.
Type 'Response' is missing the following properties from type 'NextResponse<unknown>': cookies, [INTERNALS]
```

for

```
import { verifySignatureAppRouter } from "@upstash/qstash/nextjs";

async function handler(request: Request) {
  const data = await request.json();

  for (let i = 0; i < 10; i++) {
    await fetch('https://firstqstashmessage.requestcatcher.com/test', {
      method: 'POST',
      body: JSON.stringify(data),
      headers: { 'Content-Type': 'application/json' }
    });
    await new Promise(resolve => setTimeout(resolve, 500));
  }


  return Response.json({ success: true });
}

export const POST = verifySignatureAppRouter(handler);
```

**Comment by ogzhanolguncu** [comment]
> Looks like this does cause existing imports to be broken. Followed the [Nextjs quickstart](https://upstash.com/docs/qstash/quickstarts/vercel-nextjs) and got this after step 5.
> 
> ```
> Package path ./dist/nextjs is not exported from package 
> ```
> 
> Also getting this type error
> 
> ```
> Argument of type '(request: Request) => Promise<Response>' is not assignable to parameter of type '((request: Request) => VerifySignatureAppRouterResponse) | ((request: NextRequest) => VerifySignatureAppRouterResponse)'.
>   Type '(request: Request) => Promise<Response>' is not assignable to type '(request: Request) => VerifySignatureAppRouterResponse'.
>     Type 'Promise<Response>' is not assignable to type 'VerifySignatureAppRouterResponse'.
>       Type 'Promise<Response>' is not assignable to type 'Promise<NextResponse<unknown>>'.
> Type 'Response' is missing the following properties from type 'NextResponse<unknown>': cookies, [INTERNALS]
> ```
> 
> for
> 
> ```
> import { verifySignatureAppRouter } from "@upstash/qstash/nextjs";
> 
> async function handler(request: Request) {
>   const data = await request.json();
> 
>   for (let i = 0; i < 10; i++) {
>     await fetch('https://firstqstashmessage.requestcatcher.com/test', {
>       method: 'POST',
>       body: JSON.stringify(data),
>       headers: { 'Content-Type': 'application/json' }
>     });
>     await new Promise(resolve => setTimeout(resolve, 500));
>   }
> 
> 
>   return Response.json({ success: true });
> }
> 
> export const POST = verifySignatureAppRouter(handler);
> ```

Yeah, sadly this change is breaking existing imports. And, I'll check nextjs import and make sure its works like this: `@upstash/qstash/nextj`

**Comment by ytkimirti** [comment]
@MeshanKhosla imports should be fixed now, if there is anything wrong ping me

**Review by MeshanKhosla — APPROVED** [review]
Looks good!

**Review by fahreddinozcan — APPROVED** [review]

**Pull request merged**
